services:
  backend:
    build: ./backendservice
    image: backendservice:1.0
    container_name: backend
    ports:
      - "8080:8080"

  client:
    build: ./clientservice
    image: clientservice:1.0
    container_name: client
    environment:
      - BACKEND_URL=http://backend:8080/api/data
    ports:
      - "8081:8081"
    depends_on:
      - backend
